import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { twMerge } from 'tailwind-merge'

import Header from '@/components/Header'
import '../globals.css'
import { ThemeProvider } from '@/components/ThemeProvider'
import Footer from '@/components/Footer'
import UnderConstruction from '@/components/UnderConstruction'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Bae - Frontend Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body
        className={twMerge(
          inter.className,
          'min-h-screen max-w-screen-lg mx-auto'
        )}>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          <UnderConstruction />
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
